"""After separate execution approval, add native selection motion to a NEW PPTX.

Input must be the deck generated by main.mjs. This is an authored, unexecuted
postprocessing stage, not a replacement Aha renderer or an Aha render receipt.
"""
import argparse
import hashlib
import io
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET
from zipfile import ZipFile

P = "http://schemas.openxmlformats.org/presentationml/2006/main"
A = "http://schemas.openxmlformats.org/drawingml/2006/main"
NS = {"p": P, "a": A}
ET.register_namespace("p", P)


def child(parent, tag, **attrs):
    return ET.SubElement(parent, f"{{{P}}}{tag}", attrs)


def motion_timing(shape_id, delta):
    timing = ET.Element(f"{{{P}}}timing")
    root = child(child(child(timing, "tnLst"), "par"), "cTn",
                 id="1", dur="indefinite", restart="never", nodeType="tmRoot")
    sequence = child(child(root, "childTnLst"), "seq", concurrent="1", nextAc="seek")
    main = child(sequence, "cTn", id="2", dur="indefinite", nodeType="mainSeq")
    click = child(child(child(main, "childTnLst"), "par"), "cTn", id="3", fill="hold")
    child(child(click, "stCondLst"), "cond", delay="indefinite")
    effect = child(child(child(click, "childTnLst"), "par"), "cTn",
                   id="4", fill="hold", nodeType="clickEffect",
                   presetClass="path", presetID="0", presetSubtype="0")
    child(child(effect, "stCondLst"), "cond", delay="0")
    motion = child(child(effect, "childTnLst"), "animMotion",
                   origin="layout", path=f"M {delta} 0 L 0 0 E",
                   pathEditMode="relative", rAng="0")
    behavior = child(motion, "cBhvr", additive="base")
    duration = child(behavior, "cTn", id="5", dur="900", fill="hold")
    child(child(duration, "stCondLst"), "cond", delay="0")
    child(child(behavior, "tgtEl"), "spTgt", spid=shape_id)
    names = child(behavior, "attrNameLst")
    child(names, "attrName").text = "ppt_x"
    child(names, "attrName").text = "ppt_y"
    for tag, event in (("prevCondLst", "onPrev"), ("nextCondLst", "onNext")):
        condition = child(child(sequence, tag), "cond", evt=event, delay="0")
        child(child(condition, "tgtEl"), "sldTgt")
    return ET.tostring(timing, encoding="unicode")


def patch_slide(data, expected, delta):
    xml = data.decode("utf-8")
    if re.search(r"<!DOCTYPE|<!ENTITY", xml, re.I):
        raise ValueError("Entity-bearing XML is not an approved generated input")
    root = ET.fromstring(xml)
    if root.find("p:timing", NS) is not None:
        raise ValueError("Existing timing must not be overwritten")
    candidates = []
    for shape in root.findall(".//p:sp", NS):
        words = "".join(node.text or "" for node in shape.findall(".//a:t", NS))
        identity = shape.find("p:nvSpPr/p:cNvPr", NS)
        position = shape.find("p:spPr/a:xfrm/a:off", NS)
        if words == expected and identity is not None and position is not None:
            candidates.append((int(position.get("x")), identity.get("id")))
    if not candidates:
        raise ValueError("Expected native result text was not found")
    x, shape_id = max(candidates)
    if x < 9 * 914400 or not shape_id or not shape_id.isdigit():
        raise ValueError("Result shape is not in the expected right-hand column")
    timing = motion_timing(shape_id, delta)
    marker = "<p:extLst" if "<p:extLst" in xml else "</p:sld>"
    if marker not in xml:
        raise ValueError("Unexpected slide XML prefix/layout")
    revised = xml.replace(marker, timing + marker, 1)
    ET.fromstring(revised)
    return revised.encode("utf-8"), shape_id


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    project = Path(__file__).resolve().parents[1]
    source, output = args.input.resolve(), args.output.resolve()
    review = output.with_suffix(output.suffix + ".motion-review.json")
    if source.suffix.lower() != ".pptx" or output.suffix.lower() != ".pptx":
        raise ValueError("Both paths must end in .pptx")
    if output.is_relative_to(project) or output.exists() or review.exists():
        raise ValueError("Use a fresh output outside the source project")
    if not output.parent.is_dir() or source.stat().st_size > 64 * 1024 * 1024:
        raise ValueError("Output parent must exist; input limit is 64 MiB")
    original = source.read_bytes()
    edits = {
        "ppt/slides/slide4.xml": ("on", "-0.2325"),
        "ppt/slides/slide5.xml": ("off", "-0.465"),
    }
    changed = []
    buffer = io.BytesIO()
    with ZipFile(io.BytesIO(original)) as incoming:
        entries = incoming.infolist()
        if len({entry.filename for entry in entries}) != len(entries):
            raise ValueError("Duplicate ZIP entries are unsupported")
        if sum(entry.file_size for entry in entries) > 128 * 1024 * 1024:
            raise ValueError("Expanded package exceeds 128 MiB")
        if any(entry.filename.startswith("_xmlsignatures/") for entry in entries):
            raise ValueError("Do not modify signed presentations")
        if not set(edits).issubset(incoming.namelist()):
            raise ValueError("Expected slides 4 and 5 are absent")
        with ZipFile(buffer, "w") as outgoing:
            for entry in entries:
                content = incoming.read(entry)
                if entry.filename in edits:
                    expected, delta = edits[entry.filename]
                    content, shape_id = patch_slide(content, expected, delta)
                    changed.append({"slide": entry.filename, "shapeId": shape_id,
                                    "durationMs": 900, "horizontalPath": delta})
                outgoing.writestr(entry, content)
    result = buffer.getvalue()
    with output.open("xb") as handle:
        handle.write(result)
    record = {
        "kind": "native-motion-postprocess-not-aha-render-receipt",
        "inputSha256": hashlib.sha256(original).hexdigest(),
        "outputSha256": hashlib.sha256(result).hexdigest(),
        "authorScriptSha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "modified": changed,
        "visualQA": "Not performed by this utility; inspect actual slide-show playback",
    }
    with review.open("x", encoding="utf-8") as handle:
        json.dump(record, handle, indent=2)


if __name__ == "__main__":
    main()
